---
abstract: 'Asynchronous IMAP handling'
author:
  - 'Tom Molesworth <net-async-imap@entitymodel.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Async-IMAP
requires:
  IO::Async: 0.34
  IO::Async::SSL: 0.04
  Protocol::IMAP: 0.002
  Socket: 0
  parent: 0
version: 0.002
