---
abstract: 'Asynchronous IMAP handling'
author:
  - 'Tom Molesworth <net-async-imap@entitymodel.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.005, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Async-IMAP
requires:
  IO::Async: 0.54
  IO::Async::SSL: 0.12
  Protocol::IMAP: 0.004
  Socket: 0
  parent: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Net-Async-IMAP
  homepage: http://search.cpan.org/dist/Net-Async-IMAP/
version: 0.004
